version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

    command: npm run start
    env_file:
      - .env
  administration-clients:
    image: 'postgres:14.0-alpine'
    restart: always
    container_name: session-tracking-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
